### PR TITLE
Bin setup

### PR DESCRIPTION
**Pull request by davetron5000**
These are changes I made that makes everything work.  I didn't change any of the app's code, so I'm not sure what was going on on your end.

1. Removed the call to load dotenv so I could hopefully see it not work
2. I added several files to run a dev environment in Docker.  This is a more advanced version of what is described in the book, but basically:
   * `Dockerfile.dx` runs Ruby 3.2.2 and Rails and is where your app can be developed
   * `docker-compose.dx.yml` runs that image + Postgres + Redis
   * `dx/*` are a bunch of scripts to manage it
3. I added `.env.development` and `.env.test`.  This is required for dotenv and this app to work because they set the value for `DATABASE_URL`

If you have docker installed, you can try this like so:

1. Check out this branch
2. `dx/setup` - this will verify your processor architecture
3. `dx/build` - this will build the docker image - might take a bit to complete
4. `dx/start` - this will start everything up
5. In another terminal do `dx/exec bash` and you'll be "logged into" the image to run the app
6. `npm install -g yarn` (I forgot to include yarn in the docker image)
7. `bin/setup` - this should complete successfully
8. `bin/ci` - should also work

Let me know if this doesn't work or if you have something in your env that is different

### CODE REVIEW

**Comment by Gutopro** [comment]
Thanks, Dave, for this, I'm a bit confused regarding the steps you gave me as I'm new to open source and the whole process. this repository exists in my docker image and from your instructions it seems I'll need to build a new image, my confusion is do I fork your already forked repo and try it out since I can't fork my own repo? sorry if this appears confusing but I'll like to understand every bit of the process, I googled a bit, but I still didn't get the clarity I needed. thank you!

**Comment by davetron5000** [comment]
Hey, no worries - git confused the heck out of me when I first had to learn it.

You can try this:

1. In your repo, add my fork:
   
   ```
   git remote add davetron5000 git@github.com:davetron5000/event-app.git
   ```
2. This allows you to see my changes as a branch:

    ```
    git fetch davetron5000
    git checkout davetron5000/bin-setup
    ```
3. At this point your repo should look exactly like my pull request.  You should be able to follow my instructions.  Of note: allt he stuff using `dx` like `dx/start` is intended to run on YOUR computer not inside Docker.  If you are already running all this inside Docker, you can skip the `dx` stuff and do `bin/setup` and *hopefully* it'll work? 🤞

**Comment by Gutopro** [comment]
hello @davetron5000 and thanks for your help, when i initially ran bin/setup i got this error 
dotenv fail
so i decided to check the .env.development and test files and i noticed this 
env
so i changed the hostname to @db and it worked

**Comment by davetron5000** [comment]
Ahhh, right.  I forgot the book uses `db`. For future reference, that value comes from the service name in `docker-compose.yml`.  The book calls it `db` and I've recently changed it locally to `postgres`.  Glad it's working!

**Comment by Gutopro** [comment]
thanks @davetron5000 I really appreciate your effort in helping young and aspiring developers become better. could you please give me any feedback and advice that could help propel me to the next level?

**Comment by davetron5000** [comment]
Happy to help!

The best advice is to get some experience building things.  If you can't get that at a job, build some stuff you would find useful yourself.  I built a web app in Rails that allows my wife and I to play our dinners for the week. We are the only ones that use it, but it's darn useful.  It was a good experience building it, since I didn't have to worry about some job not liking what I did :)

But, working with more experienced people also helps, too.  For that, you kinda need a job-type thing :(

**Comment by Gutopro** [comment]
thank you so much @davetron5000 I really appreciate all your efforts and i won't forget what you just taught me. i wish all the best and hope to work with you some more.

**Pull request merged**
